// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.1
// source: proto/integration.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Integrator_Integrate_FullMethodName       = "/integration.Integrator/Integrate"
	Integrator_IntegrateStream_FullMethodName = "/integration.Integrator/IntegrateStream"
)

// IntegratorClient is the client API for Integrator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IntegratorClient interface {
	Integrate(ctx context.Context, in *IntegrationRequest, opts ...grpc.CallOption) (*IntegrationResponse, error)
	IntegrateStream(ctx context.Context, in *IntegrationRequest, opts ...grpc.CallOption) (Integrator_IntegrateStreamClient, error)
}

type integratorClient struct {
	cc grpc.ClientConnInterface
}

func NewIntegratorClient(cc grpc.ClientConnInterface) IntegratorClient {
	return &integratorClient{cc}
}

func (c *integratorClient) Integrate(ctx context.Context, in *IntegrationRequest, opts ...grpc.CallOption) (*IntegrationResponse, error) {
	out := new(IntegrationResponse)
	err := c.cc.Invoke(ctx, Integrator_Integrate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integratorClient) IntegrateStream(ctx context.Context, in *IntegrationRequest, opts ...grpc.CallOption) (Integrator_IntegrateStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Integrator_ServiceDesc.Streams[0], Integrator_IntegrateStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &integratorIntegrateStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Integrator_IntegrateStreamClient interface {
	Recv() (*IntegrationResponse, error)
	grpc.ClientStream
}

type integratorIntegrateStreamClient struct {
	grpc.ClientStream
}

func (x *integratorIntegrateStreamClient) Recv() (*IntegrationResponse, error) {
	m := new(IntegrationResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// IntegratorServer is the server API for Integrator service.
// All implementations must embed UnimplementedIntegratorServer
// for forward compatibility
type IntegratorServer interface {
	Integrate(context.Context, *IntegrationRequest) (*IntegrationResponse, error)
	IntegrateStream(*IntegrationRequest, Integrator_IntegrateStreamServer) error
	mustEmbedUnimplementedIntegratorServer()
}

// UnimplementedIntegratorServer must be embedded to have forward compatible implementations.
type UnimplementedIntegratorServer struct {
}

func (UnimplementedIntegratorServer) Integrate(context.Context, *IntegrationRequest) (*IntegrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Integrate not implemented")
}
func (UnimplementedIntegratorServer) IntegrateStream(*IntegrationRequest, Integrator_IntegrateStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method IntegrateStream not implemented")
}
func (UnimplementedIntegratorServer) mustEmbedUnimplementedIntegratorServer() {}

// UnsafeIntegratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IntegratorServer will
// result in compilation errors.
type UnsafeIntegratorServer interface {
	mustEmbedUnimplementedIntegratorServer()
}

func RegisterIntegratorServer(s grpc.ServiceRegistrar, srv IntegratorServer) {
	s.RegisterService(&Integrator_ServiceDesc, srv)
}

func _Integrator_Integrate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntegrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegratorServer).Integrate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Integrator_Integrate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegratorServer).Integrate(ctx, req.(*IntegrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Integrator_IntegrateStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(IntegrationRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IntegratorServer).IntegrateStream(m, &integratorIntegrateStreamServer{stream})
}

type Integrator_IntegrateStreamServer interface {
	Send(*IntegrationResponse) error
	grpc.ServerStream
}

type integratorIntegrateStreamServer struct {
	grpc.ServerStream
}

func (x *integratorIntegrateStreamServer) Send(m *IntegrationResponse) error {
	return x.ServerStream.SendMsg(m)
}

// Integrator_ServiceDesc is the grpc.ServiceDesc for Integrator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Integrator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "integration.Integrator",
	HandlerType: (*IntegratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Integrate",
			Handler:    _Integrator_Integrate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "IntegrateStream",
			Handler:       _Integrator_IntegrateStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/integration.proto",
}
