// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/integration.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IntegrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Function      string                 `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"`
	LowerBound    float64                `protobuf:"fixed64,2,opt,name=lower_bound,json=lowerBound,proto3" json:"lower_bound,omitempty"`
	UpperBound    float64                `protobuf:"fixed64,3,opt,name=upper_bound,json=upperBound,proto3" json:"upper_bound,omitempty"`
	Partitions    int64                  `protobuf:"varint,4,opt,name=partitions,proto3" json:"partitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegrationRequest) Reset() {
	*x = IntegrationRequest{}
	mi := &file_proto_integration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrationRequest) ProtoMessage() {}

func (x *IntegrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_integration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrationRequest.ProtoReflect.Descriptor instead.
func (*IntegrationRequest) Descriptor() ([]byte, []int) {
	return file_proto_integration_proto_rawDescGZIP(), []int{0}
}

func (x *IntegrationRequest) GetFunction() string {
	if x != nil {
		return x.Function
	}
	return ""
}

func (x *IntegrationRequest) GetLowerBound() float64 {
	if x != nil {
		return x.LowerBound
	}
	return 0
}

func (x *IntegrationRequest) GetUpperBound() float64 {
	if x != nil {
		return x.UpperBound
	}
	return 0
}

func (x *IntegrationRequest) GetPartitions() int64 {
	if x != nil {
		return x.Partitions
	}
	return 0
}

type IntegrationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Result         float64                `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
	ErrorEstimate  float64                `protobuf:"fixed64,2,opt,name=error_estimate,json=errorEstimate,proto3" json:"error_estimate,omitempty"`
	PartitionsUsed int64                  `protobuf:"varint,3,opt,name=partitions_used,json=partitionsUsed,proto3" json:"partitions_used,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IntegrationResponse) Reset() {
	*x = IntegrationResponse{}
	mi := &file_proto_integration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrationResponse) ProtoMessage() {}

func (x *IntegrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_integration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrationResponse.ProtoReflect.Descriptor instead.
func (*IntegrationResponse) Descriptor() ([]byte, []int) {
	return file_proto_integration_proto_rawDescGZIP(), []int{1}
}

func (x *IntegrationResponse) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *IntegrationResponse) GetErrorEstimate() float64 {
	if x != nil {
		return x.ErrorEstimate
	}
	return 0
}

func (x *IntegrationResponse) GetPartitionsUsed() int64 {
	if x != nil {
		return x.PartitionsUsed
	}
	return 0
}

var File_proto_integration_proto protoreflect.FileDescriptor

const file_proto_integration_proto_rawDesc = "" +
	"\n" +
	"\x17proto/integration.proto\x12\vintegration\"\x92\x01\n" +
	"\x12IntegrationRequest\x12\x1a\n" +
	"\bfunction\x18\x01 \x01(\tR\bfunction\x12\x1f\n" +
	"\vlower_bound\x18\x02 \x01(\x01R\n" +
	"lowerBound\x12\x1f\n" +
	"\vupper_bound\x18\x03 \x01(\x01R\n" +
	"upperBound\x12\x1e\n" +
	"\n" +
	"partitions\x18\x04 \x01(\x03R\n" +
	"partitions\"}\n" +
	"\x13IntegrationResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x01R\x06result\x12%\n" +
	"\x0eerror_estimate\x18\x02 \x01(\x01R\rerrorEstimate\x12'\n" +
	"\x0fpartitions_used\x18\x03 \x01(\x03R\x0epartitionsUsed2\xb4\x01\n" +
	"\n" +
	"Integrator\x12N\n" +
	"\tIntegrate\x12\x1f.integration.IntegrationRequest\x1a .integration.IntegrationResponse\x12V\n" +
	"\x0fIntegrateStream\x12\x1f.integration.IntegrationRequest\x1a .integration.IntegrationResponse0\x01B\"Z github.com/hard/go-service/protob\x06proto3"

var (
	file_proto_integration_proto_rawDescOnce sync.Once
	file_proto_integration_proto_rawDescData []byte
)

func file_proto_integration_proto_rawDescGZIP() []byte {
	file_proto_integration_proto_rawDescOnce.Do(func() {
		file_proto_integration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_integration_proto_rawDesc), len(file_proto_integration_proto_rawDesc)))
	})
	return file_proto_integration_proto_rawDescData
}

var file_proto_integration_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_integration_proto_goTypes = []any{
	(*IntegrationRequest)(nil),  // 0: integration.IntegrationRequest
	(*IntegrationResponse)(nil), // 1: integration.IntegrationResponse
}
var file_proto_integration_proto_depIdxs = []int32{
	0, // 0: integration.Integrator.Integrate:input_type -> integration.IntegrationRequest
	0, // 1: integration.Integrator.IntegrateStream:input_type -> integration.IntegrationRequest
	1, // 2: integration.Integrator.Integrate:output_type -> integration.IntegrationResponse
	1, // 3: integration.Integrator.IntegrateStream:output_type -> integration.IntegrationResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_integration_proto_init() }
func file_proto_integration_proto_init() {
	if File_proto_integration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_integration_proto_rawDesc), len(file_proto_integration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_integration_proto_goTypes,
		DependencyIndexes: file_proto_integration_proto_depIdxs,
		MessageInfos:      file_proto_integration_proto_msgTypes,
	}.Build()
	File_proto_integration_proto = out.File
	file_proto_integration_proto_goTypes = nil
	file_proto_integration_proto_depIdxs = nil
}
