# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import integration_pb2 as integration__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in integration_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IntegratorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Integrate = channel.unary_unary(
                '/integration.Integrator/Integrate',
                request_serializer=integration__pb2.IntegrationRequest.SerializeToString,
                response_deserializer=integration__pb2.IntegrationResponse.FromString,
                _registered_method=True)
        self.IntegrateStream = channel.unary_stream(
                '/integration.Integrator/IntegrateStream',
                request_serializer=integration__pb2.IntegrationRequest.SerializeToString,
                response_deserializer=integration__pb2.IntegrationResponse.FromString,
                _registered_method=True)


class IntegratorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Integrate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IntegrateStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IntegratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Integrate': grpc.unary_unary_rpc_method_handler(
                    servicer.Integrate,
                    request_deserializer=integration__pb2.IntegrationRequest.FromString,
                    response_serializer=integration__pb2.IntegrationResponse.SerializeToString,
            ),
            'IntegrateStream': grpc.unary_stream_rpc_method_handler(
                    servicer.IntegrateStream,
                    request_deserializer=integration__pb2.IntegrationRequest.FromString,
                    response_serializer=integration__pb2.IntegrationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'integration.Integrator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('integration.Integrator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Integrator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Integrate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/integration.Integrator/Integrate',
            integration__pb2.IntegrationRequest.SerializeToString,
            integration__pb2.IntegrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IntegrateStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/integration.Integrator/IntegrateStream',
            integration__pb2.IntegrationRequest.SerializeToString,
            integration__pb2.IntegrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
