# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: integration.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'integration.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11integration.proto\x12\x0bintegration\"d\n\x12IntegrationRequest\x12\x10\n\x08\x66unction\x18\x01 \x01(\t\x12\x13\n\x0blower_bound\x18\x02 \x01(\x01\x12\x13\n\x0bupper_bound\x18\x03 \x01(\x01\x12\x12\n\npartitions\x18\x04 \x01(\x03\"V\n\x13IntegrationResponse\x12\x0e\n\x06result\x18\x01 \x01(\x01\x12\x16\n\x0e\x65rror_estimate\x18\x02 \x01(\x01\x12\x17\n\x0fpartitions_used\x18\x03 \x01(\x03\x32\xb4\x01\n\nIntegrator\x12N\n\tIntegrate\x12\x1f.integration.IntegrationRequest\x1a .integration.IntegrationResponse\x12V\n\x0fIntegrateStream\x12\x1f.integration.IntegrationRequest\x1a .integration.IntegrationResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'integration_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INTEGRATIONREQUEST']._serialized_start=34
  _globals['_INTEGRATIONREQUEST']._serialized_end=134
  _globals['_INTEGRATIONRESPONSE']._serialized_start=136
  _globals['_INTEGRATIONRESPONSE']._serialized_end=222
  _globals['_INTEGRATOR']._serialized_start=225
  _globals['_INTEGRATOR']._serialized_end=405
# @@protoc_insertion_point(module_scope)
